language: scala
script:
  - sbt -Ddotty.travis.build=yes update compile test
jdk:
  - oraclejdk7
notifications:
  email:
    - reports@d-d.me
before_install:
  - cd ..
  - git clone https://github.com/scala/scala.git
  - cd dotty
